-- Retrieves the Vospace repository size BY DAY and up to the date configured.
SELECT LOGIN_TIMESTAMP::DATE AS Login, SUM(QUOTA) AS Size
FROM CONTROLS.ACCESS_LOG AS A
INNER JOIN (SELECT MAX(ACCESS_LOG_OID) AS ACCESS_LOG_OID
        FROM CONTROLS.ACCESS_LOG AS A
        LEFT JOIN CONTROLS.USER AS U
        ON A.USER_ID=U.USER_OID
        WHERE A.LOGIN_TIMESTAMP <= '2014-09-19 00:00:00'
        GROUP BY U.UNAME, A.LOGIN_TIMESTAMP::DATE) AS B
ON A.ACCESS_LOG_OID=B.ACCESS_LOG_OID
GROUP BY LOGIN_TIMESTAMP::DATE
ORDER BY Login ASC;

-- Get the evolution of the users registered BY DAY between the dates.
SELECT COUNT(*), REGISTER_DATE::DATE AS Creation
FROM CONTROLS.USER
WHERE REGISTER_DATE >= '2014-01-01 00:00:00' AND
REGISTER_DATE <= '2014-09-20 00:00:00'
GROUP BY REGISTER_DATE::DATE;

-- Get the evolution of the session time by access day between two dates
SELECT ACCESS_LOG_OID, LOGOUT_TIMESTAMP, (A.LOGOUT_TIMESTAMP - A.LOGIN_TIMESTAMP) AS session_time
FROM CONTROLS.ACCESS_LOG AS A
WHERE A.LOGOUT_TIMESTAMP IS NOT NULL AND
    A.LOGIN_TIMESTAMP >= '2014-09-01 00:00:00' AND
    A.LOGOUT_TIMESTAMP <= '2014-09-20 00:00:00';
    
-- Get the session average BY DAY between two dates
SELECT AVG(A.LOGOUT_TIMESTAMP - A.LOGIN_TIMESTAMP) AS session_time_average, A.LOGIN_TIMESTAMP::DATE AS ACCESS_DATE
FROM CONTROLS.ACCESS_LOG AS A
WHERE A.LOGOUT_TIMESTAMP IS NOT NULL AND
    A.LOGIN_TIMESTAMP >= '2014-09-01 00:00:00' AND
    A.LOGOUT_TIMESTAMP <= '2014-09-20 00:00:00'
GROUP BY A.LOGIN_TIMESTAMP::DATE
ORDER BY ACCESS_DATE ASC;

-- Get the size of data transferred (upload/download) by DAY
-- OPERATION_TYPE = '0' -> push_to_vospace (cmd line) 
-- OPERATION_TYPE = '1' -> upload (web client)
-- OPERATION_TYPE = '2' -> pull_to_vospace (service-to-service)
-- OPERATION_TYPE = '3' -> pull_from_vospace_POST (cmd line)
-- OPERATION_TYPE = '4' -> pull_from_vospace_GET = download (web client)
-- OPERATION_TYPE = '5' -> push_from_vospace (service-to-service)
SELECT START_TIMESTAMP::DATE, SUM(TOTAL_SIZE) AS size
FROM CONTROLS.TRANSFER_LOG
WHERE OPERATION_TYPE = '1' AND
START_TIMESTAMP >= '2014-01-01 00:00:00' AND
START_TIMESTAMP <= '2014-09-20 00:00:00'
GROUP BY START_TIMESTAMP::DATE;



