package esac.archive.vospace.persistence.model;
// Generated Apr 7, 2014 5:34:20 PM by Hibernate Tools 3.3.0.GA


import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CapabilityParam generated by hbm2java
 */
@Entity
@Table(name="capability_param"
    ,schema="vos"
)
public class CapabilityParam  implements java.io.Serializable {


     private Integer capabilityParamOid;
     private VoCapability voCapability;
     private String name;
     private String value;

    public CapabilityParam() {
    }

    public CapabilityParam(Integer capabilityParamOid, VoCapability voCapability, String name, String value) {
       this.capabilityParamOid = capabilityParamOid;
       this.voCapability = voCapability;
       this.name = name;
       this.value = value;
    }
   
    @SequenceGenerator(name="generator", sequenceName="capability_param_capability_param_oid_seq")
    @Id 
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="capability_param_oid", unique=true, nullable=false)
    public Integer getCapabilityParamOid() {
        return this.capabilityParamOid;
    }
    
    public void setCapabilityParamOid(Integer capabilityParamOid) {
        this.capabilityParamOid = capabilityParamOid;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vo_capability_id", nullable=false)
    public VoCapability getVoCapability() {
        return this.voCapability;
    }
    
    public void setVoCapability(VoCapability voCapability) {
        this.voCapability = voCapability;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


