package esac.archive.vospace.persistence.model;
// Generated Mar 29, 2014 6:27:54 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * ContainerNode generated by hbm2java
 */
@Entity
@Table(name="container_node"
    ,schema="vos"
)
public class ContainerNode extends DataNode {

    
    private Set<Node> childrens = new HashSet<Node>(0);

    public ContainerNode() {
    }
    
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="containerNode")
    @OrderBy("name ASC")
    public Set<Node> getChildrens() {
        return this.childrens;
    }
    
    public void setChildrens(Set<Node> childrens) {
        this.childrens = childrens;
    }
    
    /*@OneToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "container_children", schema = "vos",
    joinColumns = { @JoinColumn(name = "parent_node_id", nullable = false, updatable = false) }, 
    inverseJoinColumns = { @JoinColumn(name = "child_node_id", nullable = false, updatable = false) })
    public Set<Node> getChildrens() {
        return this.childrens;
    }
    
    public void setChildrens(Set<Node> childrens) {
        this.childrens = childrens;
    }*/
    
}


