package esac.archive.vospace.persistence.model;
// Generated Mar 29, 2014 6:27:54 PM by Hibernate Tools 3.3.0.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * DataNode generated by hbm2java
 */
@Entity
@Table(name="data_node"
    ,schema="vos"
)
public class DataNode extends Node {

    private boolean busy;
     
    private Set<VoView> views = new HashSet<VoView>(0);

    public DataNode() {
    }
	
    public DataNode(boolean busy) {
        this.busy = busy;
    }
    
    @Column(name="busy", nullable=false)
    public boolean isBusy() {
        return this.busy;
    }
    
    public void setBusy(boolean busy) {
        this.busy = busy;
    }
    
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "node_view", schema = "vos",
    joinColumns = { @JoinColumn(name = "node_id", nullable = false, updatable = false) }, 
    inverseJoinColumns = { @JoinColumn(name = "view_id", nullable = false, updatable = false) })
    public Set<VoView> getViews() {
        return this.views;
    }
    
    public void setViews(Set<VoView> nodeViews) {
        this.views = nodeViews;
    }

}


