package esac.archive.vospace.persistence.model;
// Generated Aug 6, 2014 11:06:34 AM by Hibernate Tools 3.3.0.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupNodeProperty generated by hbm2java
 */
@Entity
@Table(name="group_node_property"
    , schema="vos"
)
public class GroupNodeProperty extends NodeProperty {

    private Set<Groups> shareGroups = new HashSet<Groups>(0);

    public GroupNodeProperty() {}

    //@OneToMany(fetch=FetchType.LAZY, mappedBy="shareNodeProperty")
    @OneToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "share_group", schema = "vos",
    joinColumns = { @JoinColumn(name = "node_property_id", nullable = false, updatable = false) }, 
    inverseJoinColumns = { @JoinColumn(name = "group_id", nullable = false, updatable = false) })
    public Set<Groups> getShareGroups() {
        return this.shareGroups;
    }
    
    public void setShareGroups(Set<Groups> shareGroups) {
        this.shareGroups = shareGroups;
    }




}


