package esac.archive.vospace.persistence.model;
// Generated Mar 29, 2014 6:27:54 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LinkNode generated by hbm2java
 */
@Entity
@Table(name="link_node"
    ,schema="vos"
)
public class LinkNode extends Node {

    private String target;

    public LinkNode() {
    }

    public LinkNode(String target) {
       this.target = target;
    }
    
    @Column(name="target", nullable=false)
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }
    
}


