package esac.archive.vospace.persistence.model;
// Generated Mar 29, 2014 6:27:54 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UnstructuredDataNode generated by hbm2java
 */
@Entity
@Table(name="unstructured_data_node"
    ,schema="vos"
)
public class UnstructuredDataNode  extends DataNode {


    public UnstructuredDataNode() {
    }

}


