package esac.archive.vospace.persistence.model;
// Generated Apr 7, 2014 5:34:20 PM by Hibernate Tools 3.3.0.GA


import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ViewParam generated by hbm2java
 */
@Entity
@Table(name="view_param"
    ,schema="vos"
)
public class ViewParam  implements java.io.Serializable {


     private Integer viewParamOid;
     private VoView voView;
     private String name;
     private String value;

    public ViewParam() {
    }

    public ViewParam(Integer viewParamOid, VoView voView, String name, String value) {
       this.viewParamOid = viewParamOid;
       this.voView = voView;
       this.name = name;
       this.value = value;
    }
   
    @SequenceGenerator(name="generator", sequenceName="view_param_view_param_oid_seq")
    @Id 
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="view_param_oid", unique=true, nullable=false)
    public Integer getViewParamOid() {
        return this.viewParamOid;
    }
    
    public void setViewParamOid(Integer viewParamOid) {
        this.viewParamOid = viewParamOid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vo_view_id", nullable=false)
    public VoView getVoView() {
        return this.voView;
    }
    
    public void setVoView(VoView voView) {
        this.voView = voView;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


