package esac.archive.vospace.persistence.model;
// Generated Mar 29, 2014 6:27:54 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * VoProperty generated by hbm2java
 */
@Entity
@Table(name="vo_property"
    ,schema="vos"
    ,uniqueConstraints = @UniqueConstraint(columnNames="uri") 
)
public class VoProperty  implements java.io.Serializable {


     private Integer voPropertyOid;
     private String uri;
     private String description;
     private boolean readonly;
     private VosType propertyType;
     
     //private Set<Node> nodes = new HashSet<Node>(0);
     
     private Set<NodeProperty> nodePropertySet = new HashSet<NodeProperty>(0);

    public VoProperty() {
    }

	
    public VoProperty(String uri, String description, boolean readonly) {
        this.uri = uri;
        this.description = description;
        this.readonly = readonly;
    }
    /*public VoProperty(String uri, String description, boolean readonly, Set<NodeProperty> nodeProperties) {
       this.name = uri;
       this.description = description;
       this.readonly = readonly;
       this.nodeProperties = nodeProperties;
    }*/
   
    @SequenceGenerator(name="generator", sequenceName="vo_property_vo_property_oid_seq")
    @Id 
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="vo_property_oid", unique=true, nullable=false)
    public Integer getVoPropertyOid() {
        return this.voPropertyOid;
    }
    
    public void setVoPropertyOid(Integer voPropertyOid) {
        this.voPropertyOid = voPropertyOid;
    }

    
    @Column(name="uri", unique=true, nullable=false)
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="readonly", nullable=false)
    public boolean isReadonly() {
        return this.readonly;
    }
    
    public void setReadonly(boolean readonly) {
        this.readonly = readonly;
    }

    /*@ManyToMany(fetch=FetchType.LAZY, mappedBy="nodeProperties")
    public Set<Node> getNodes() {
        return this.nodes;
    }
    
    public void setNodes(Set<Node> nodeProperties) {
        this.nodes = nodeProperties;
    }*/
    
    /*@OneToMany(fetch=FetchType.LAZY, mappedBy="voProperty")
    public Set<NodeProperty> getNodeProperties() {
        return this.nodes;
    }
    
    public void setNodeProperties(Set<NodeProperty> nodeProperties) {
        this.nodes = nodeProperties;
    }*/
    
    @Enumerated(EnumType.STRING)
    @Column(name="property_type")
    public VosType getPropertyType() {
        return this.propertyType;
    }
    
    public void setPropertyType(VosType propertyType) {
        this.propertyType = propertyType;
    }


    /**
     * @return the nodePropertySet
     */
    @OneToMany(fetch=FetchType.LAZY, mappedBy="voProperty")
    public final Set<NodeProperty> getNodePropertySet() {
        return nodePropertySet;
    }


    /**
     * @param nodePropertySet the nodePropertySet to set
     */
    public final void setNodePropertySet(Set<NodeProperty> nodePropertySet) {
        this.nodePropertySet = nodePropertySet;
    }
}


