package esac.archive.vospace.persistence.model;
// Generated Mar 29, 2014 6:27:54 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Enumerated;
import javax.persistence.EnumType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * VoView generated by hbm2java
 */
@Entity
@Table(name="vo_view"
    ,schema="vos"
)
public class VoView  implements java.io.Serializable {


     private Integer voViewOid;
     private String uri;
     private boolean original;
     private VosType viewType;
     
     private Set<ViewParam> viewParams = new HashSet<ViewParam>(0);
     private Set<DataNode> nodes = new HashSet<DataNode>(0);    

    public VoView() {
    }

	
    public VoView(String uri, boolean original, VosType viewType) {
        this.uri = uri;
        this.original = original;
        this.viewType = viewType;
    }
   
    @SequenceGenerator(name="generator", sequenceName="vo_view_vo_view_oid_seq")
    @Id
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="vo_view_oid", unique=true, nullable=false)
    public Integer getVoViewOid() {
        return this.voViewOid;
    }
    
    public void setVoViewOid(Integer voViewOid) {
        this.voViewOid = voViewOid;
    }

    
    @Column(name="uri", unique=true, nullable=false)
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    
    @Column(name="original", nullable=false)
    public boolean isOriginal() {
        return this.original;
    }
    
    public void setOriginal(boolean original) {
        this.original = original;
    }

    @Enumerated(EnumType.STRING)
    @Column(name="view_type", nullable=false)
    public VosType getViewType() {
        return this.viewType;
    }
    
    public void setViewType(VosType viewType) {
        this.viewType = viewType;
    }

    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="voView")
    public Set<ViewParam> getViewParams() {
        return this.viewParams;
    }
    
    public void setViewParams(Set<ViewParam> viewParams) {
        this.viewParams = viewParams;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "views")
    public Set<DataNode> getNodeViews() {
        return this.nodes;
    }
    
    public void setNodeViews(Set<DataNode> nodeViews) {
        this.nodes = nodeViews;
    }

}


