package esac.archive.vospace.persistence.model.controls;
// Generated Sep 11, 2014 5:28:54 PM by Hibernate Tools 3.3.0.GA


import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataMngLog generated by hbm2java
 */
@Entity
@Table(name="data_mng_log"
    ,schema="controls"
)
public class DataMngLog  implements java.io.Serializable {


     private Integer dataMngLogOid;
     private User user;
     private Date startTimestamp;
     private Date stopTimestamp;
     private DataMngType operationType;
     private String nodeSource;
     private String nodeTarget;
     private Long size;

    public DataMngLog() {
    }

	
    public DataMngLog(Integer dataMngLogOid, User user, Date startTimestamp, DataMngType operationType, String nodeSource) {
        this.dataMngLogOid = dataMngLogOid;
        this.user = user;
        this.startTimestamp = startTimestamp;
        this.operationType = operationType;
        this.nodeSource = nodeSource;
    }
    public DataMngLog(Integer dataMngLogOid, User user, Date startTimestamp, Date stopTimestamp, DataMngType operationType, String nodeSource, String nodeTarget, Long size) {
       this.dataMngLogOid = dataMngLogOid;
       this.user = user;
       this.startTimestamp = startTimestamp;
       this.stopTimestamp = stopTimestamp;
       this.operationType = operationType;
       this.nodeSource = nodeSource;
       this.nodeTarget = nodeTarget;
       this.size = size;
    }
   
    @SequenceGenerator(name="generator", sequenceName="controls.data_mng_log_data_mng_log_oid_seq")
    @Id
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="data_mng_log_oid", unique=true, nullable=false)
    public Integer getDataMngLogOid() {
        return this.dataMngLogOid;
    }
    
    public void setDataMngLogOid(Integer dataMngLogOid) {
        this.dataMngLogOid = dataMngLogOid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_timestamp", nullable=false, length=29)
    public Date getStartTimestamp() {
        return this.startTimestamp;
    }
    
    public void setStartTimestamp(Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="stop_timestamp", length=29)
    public Date getStopTimestamp() {
        return this.stopTimestamp;
    }
    
    public void setStopTimestamp(Date stopTimestamp) {
        this.stopTimestamp = stopTimestamp;
    }

    
    @Column(name="operation_type", nullable=false)
    public DataMngType getOperationType() {
        return this.operationType;
    }
    
    public void setOperationType(DataMngType operationType) {
        this.operationType = operationType;
    }

    
    @Column(name="node_source", nullable=false)
    public String getNodeSource() {
        return this.nodeSource;
    }
    
    public void setNodeSource(String nodeSource) {
        this.nodeSource = nodeSource;
    }

    
    @Column(name="node_target")
    public String getNodeTarget() {
        return this.nodeTarget;
    }
    
    public void setNodeTarget(String nodeTarget) {
        this.nodeTarget = nodeTarget;
    }

    
    @Column(name="size")
    public Long getSize() {
        return this.size;
    }
    
    public void setSize(Long size) {
        this.size = size;
    }




}


