package esac.archive.vospace.persistence.model.controls;
// Generated Sep 11, 2014 5:28:54 PM by Hibernate Tools 3.3.0.GA


import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MetadataRetrievalLog generated by hbm2java
 */
@Entity
@Table(name="metadata_retrieval_log"
    ,schema="controls"
)
public class MetadataRetrievalLog  implements java.io.Serializable {


     private Integer metadataRetrievalLogOid;
     private User user;
     private Date startTimestamp;
     private Date stopTimestamp;
     private MetadataRetrievalType operationType;

    public MetadataRetrievalLog() {
    }

	
    public MetadataRetrievalLog(Integer metadataRetrievalLogOid, User user, Date startTimestamp, MetadataRetrievalType operationType) {
        this.metadataRetrievalLogOid = metadataRetrievalLogOid;
        this.user = user;
        this.startTimestamp = startTimestamp;
        this.operationType = operationType;
    }
    public MetadataRetrievalLog(Integer metadataRetrievalLogOid, User user, Date startTimestamp, Date stopTimestamp, MetadataRetrievalType operationType) {
       this.metadataRetrievalLogOid = metadataRetrievalLogOid;
       this.user = user;
       this.startTimestamp = startTimestamp;
       this.stopTimestamp = stopTimestamp;
       this.operationType = operationType;
    }
   
    @SequenceGenerator(name="generator", sequenceName="controls.metadata_retrieval_log_metadata_retrieval_log_oid_seq")
    @Id
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="metadata_retrieval_log_oid", unique=true, nullable=false)
    public Integer getMetadataRetrievalLogOid() {
        return this.metadataRetrievalLogOid;
    }
    
    public void setMetadataRetrievalLogOid(Integer metadataRetrievalLogOid) {
        this.metadataRetrievalLogOid = metadataRetrievalLogOid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_timestamp", nullable=false, length=29)
    public Date getStartTimestamp() {
        return this.startTimestamp;
    }
    
    public void setStartTimestamp(Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="stop_timestamp", length=29)
    public Date getStopTimestamp() {
        return this.stopTimestamp;
    }
    
    public void setStopTimestamp(Date stopTimestamp) {
        this.stopTimestamp = stopTimestamp;
    }

    
    @Column(name="operation_type", nullable=false)
    public MetadataRetrievalType getOperationType() {
        return this.operationType;
    }
    
    public void setOperationType(MetadataRetrievalType operationType) {
        this.operationType = operationType;
    }




}


