package esac.archive.vospace.persistence.model.controls;
// Generated Sep 11, 2014 5:28:54 PM by Hibernate Tools 3.3.0.GA


import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    , uniqueConstraints = @UniqueConstraint(columnNames="uname")     ,schema="controls"
)
public class User  implements java.io.Serializable {


     private Integer userOid;
     private String uname;
     private String surname;
     private String institute;
     private String address1;
     private String address2;
     private String town;
     private String state;
     private Integer zipCode;
     private String country;
     private String mail;
     private Integer phoneNumber;
     private String fax;
     private Date registerDate;
     /*private Set<Group> groups = new HashSet<Group>(0);
     private Set<ShareLog> shareLogs = new HashSet<ShareLog>(0);
     private Set<DataMngLog> dataMngLogs = new HashSet<DataMngLog>(0);
     private Set<AccessLog> accessLogs = new HashSet<AccessLog>(0);
     private Set<TransferLog> transferLogs = new HashSet<TransferLog>(0);
     private Set<MetadataRetrievalLog> metadataRetrievalLogs = new HashSet<MetadataRetrievalLog>(0);*/

    public User() {
    }

	
    public User(Integer userOid, String uname, String surname, String mail, Date registerDate) {
        this.userOid = userOid;
        this.uname = uname;
        this.surname = surname;
        this.mail = mail;
        this.registerDate = registerDate;
    }
    public User(Integer userOid, String uname, String surname, String institute, String address1, String address2, String town, String state, Integer zipCode, String country, String mail, Integer phoneNumber, String fax, Date registerDate/*, Set<Group> groups, Set<ShareLog> shareLogs, Set<DataMngLog> dataMngLogs, Set<AccessLog> accessLogs, Set<TransferLog> transferLogs, Set<MetadataRetrievalLog> metadataRetrievalLogs*/) {
       this.userOid = userOid;
       this.uname = uname;
       this.surname = surname;
       this.institute = institute;
       this.address1 = address1;
       this.address2 = address2;
       this.town = town;
       this.state = state;
       this.zipCode = zipCode;
       this.country = country;
       this.mail = mail;
       this.phoneNumber = phoneNumber;
       this.fax = fax;
       this.registerDate = registerDate;
       /*this.groups = groups;
       this.shareLogs = shareLogs;
       this.dataMngLogs = dataMngLogs;
       this.accessLogs = accessLogs;
       this.transferLogs = transferLogs;
       this.metadataRetrievalLogs = metadataRetrievalLogs;*/
    }
   
    @SequenceGenerator(name="generator", sequenceName="controls.user_user_oid_seq")
    @Id
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="user_oid", unique=true, nullable=false)
    public Integer getUserOid() {
        return this.userOid;
    }
    
    public void setUserOid(Integer userOid) {
        this.userOid = userOid;
    }

    
    @Column(name="uname", unique=true, nullable=false)
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }

    
    @Column(name="surname", nullable=false)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="institute")
    public String getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(String institute) {
        this.institute = institute;
    }

    
    @Column(name="address1")
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="address2")
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="town")
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }

    
    @Column(name="state")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="zip_code")
    public Integer getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="mail", nullable=false)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="phone_number")
    public Integer getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="fax")
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="register_date", length=29)
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /*@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Group> getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set<Group> groups) {
        this.groups = groups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<ShareLog> getShareLogs() {
        return this.shareLogs;
    }
    
    public void setShareLogs(Set<ShareLog> shareLogs) {
        this.shareLogs = shareLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<DataMngLog> getDataMngLogs() {
        return this.dataMngLogs;
    }
    
    public void setDataMngLogs(Set<DataMngLog> dataMngLogs) {
        this.dataMngLogs = dataMngLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<AccessLog> getAccessLogs() {
        return this.accessLogs;
    }
    
    public void setAccessLogs(Set<AccessLog> accessLogs) {
        this.accessLogs = accessLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<TransferLog> getTransferLogs() {
        return this.transferLogs;
    }
    
    public void setTransferLogs(Set<TransferLog> transferLogs) {
        this.transferLogs = transferLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<MetadataRetrievalLog> getMetadataRetrievalLogs() {
        return this.metadataRetrievalLogs;
    }
    
    public void setMetadataRetrievalLogs(Set<MetadataRetrievalLog> metadataRetrievalLogs) {
        this.metadataRetrievalLogs = metadataRetrievalLogs;
    }*/




}


